
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: photogram_development

test:
  <<: *default
  database: photogram_test

production:
  <<: *default
  database: photogram_production
